version: "3.7"
services:
  nginx:
    build: nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - "/home/aloiseau/data/websites:/var/www/html"
    networks:
      - wpnet
    depends_on:
      - wordpress
    restart: always
    #env mysql



  wordpress:
    build: wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - "/home/aloiseau/data/websites:/var/www/html"
    networks:
      - wpnet
      - dbnet
    depends_on:
      - mariadb
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      MYSQL_HOST:       ${MYSQL_HOST}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_PWD:           ${WP_PWD}
      WP_EMAIL:         ${WP_EMAIL}
    restart: always

  mariadb:
    build: mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "/home/aloiseau/data/databases:/var/lib/mysql"
    networks:
      - dbnet
    restart: always
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
    

    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
  #wordpress:
   # build: srcs/wordpress/
    #container_name: wordpress
    #volumes:
    #  - "~/Desktop/inception/website:/var/www/html"
    #depends_on:
    #  - mariadb
    #networks:
    #  - frontend
    #  - backend
#    restart: always


networks:
  dbnet:
  wpnet: